[package]
name = "nub-vcs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
walkdir = "2.5"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
colored = "3.0.0"

[dev-dependencies]
tempfile = "3.10"